name='PyShort',
version='0.23',
description='a python SSH tool',
license='MIT',
packages=['hellostackoverflow'],
author='Benjamin Gerfelder',
author_email='null',
keywords=['SSH', 'TERMINAL', 'SOCKET'],
url='https://github.com/XSS6_2b2t'
